# Python Introduction

_Python_ is high-level, interpreted, weakly typed, multi-paradigm, and general purpose programming language.

## Variables in Python

In Python, __variables__ are used to _store_ data values. A __variable__ is created when a value is assigned to it using the _assignment operator_ (=). 

For example, to assign the value $10$ to a _variable_ named `x`, we can use the following code:

```python
x = 10
```

After the assignment, the _variable_ `x` will hold the value $10$, and we can use it in our code to perform operations or manipulate the data.

__Variables__ in Python are _dynamically typed_, which means that the type of a variable is determined at _runtime_ based on the value assigned to it. This allows us to assign different types of values to the same variable.

Python also supports _multiple assignment_, where we can assign values to multiple variables in a single line. For example:

```python
a, b, c = 1, 2, 3
```

In this case, the values $1$, $2$, and $3$ are assigned to _variables_ `a`, `b`, and `c` respectively.

__Variables__ in Python are _case-sensitive_, which means that `x` and `X` are considered as _different_ variables.

Overall, variables in Python are a fundamental concept that allows us to store and manipulate data in our programs.
```
```

> mi nota

In [ ]:
# create variables
x = 5
print("Value of x:", x)

# get type
print("Type of x:", type(x))

# get memory reference
print("Memory reference of x:",  (x))

Value of x: 5
Type of x: <class 'int'>
Memory reference of x: 137054778013016

## Conditionals

Conditionals are used to make decisions in a program based on certain conditions.
In _Python_, conditionals are implemented using `if`, `elif`, and `else` statements.

- The `if` statement is used to check a condition and execute a block of code if the condition is __true__.
- The `elif` statement is used to check additional conditions if the previous conditions are __false__.
- The `else` statement is used to execute a block of code if none of the previous conditions are __true__.

__Conditionals__ allow the program to take different paths based on the values of variables or the result of _comparisons_.
They are essential for controlling the _flow of execution_ in a program and making it more dynamic and responsive.

In [9]:
# simple conditional
if x > 15: 
    x = x + 2
    print("Result:", x)

In [11]:
# nested conditional
answer = input("tiene hambre?")
if answer == "si":
    lugar = input("Distripizza?")
    if lugar == "si":
        print("Result:", "Vamos por Pizza")
    else:
        print("Toco papadictos")
else:
    print("Toco tintico")

Toco tintico

In [ ]:
# elif conditional
genre = input("Qué genero de película vemos?")
if genre == "thriller":
    print("Result:", "Shutter Island")
elif genre == "comedy":
    print("Result:", "White Chicks")
elif genre == "black and white":
    print("Result:", "Monk")
elif genre == "cartoon":
    print("Result:", "Coyote Vs ACME")
else:
    print("Result:", "Avengers")

Result: Avengers

## Loops and Range

### Range

The `range` _function_ in _Python_ generates a __sequence of numbers__ within a specified range. It is commonly used in for loops to iterate over a sequence of numbers. The `range` function can take up to _three arguments_: start, stop, and step. The `start` argument specifies the starting value of the sequence (default is $0$), the `stop` argument specifies the ending value (exclusive), and the `step` argument specifies the increment (default is $1$). The `range` _function_ returns an __iterable object__ that can be converted to a list or used directly in a loop.

### Loops

__Loops__ are control structures that allow us to repeat a block of code multiple times.
In _Python_, there are two types of _loops_: the `for` loop and the `while` loop.

- The `for` loop is used to iterate over a __sequence__ (such as a list, tuple, or string) or other iterable objects. It executes a block of code for _each item_ in the sequence. The loop variable takes on the value of each item in the sequence, _one by one_.
- The `while` loop is used to repeatedly execute a block of code as long as a __certain condition__ is ___true___. It continues to execute the code until the condition becomes ___false___. 
 
Both types of loops can be used to automate repetitive tasks and make the code more efficient.

In [16]:
# range just with stop
print("Range just with stop:", list(range(21)))

# range with start and stop
print("Range with start and stop:", list(range(90, 100)))

# range jumping by odd numbers
print("Range jumping by odd numbers:", list(range(1, 50, 2)))

# range making a countdown
print("Range making a countdown:", list(range(10, 0, -1)))

Range just with stop: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Range with start and stop: [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Range jumping by odd numbers: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
Range making a countdown: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [18]:
# while loop
while True:
    x = int(input("Ingrese número:"))
    if x == 0:
        break

In [19]:
# for loop 
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [25]:
# while loop with continue 
n = 0
while n <= 20:
    if n % 3 == 0:
        print(n)
        n += 1
        continue
    print(n, "this is not a multiple of 3")
    n += 1

0
1 this is not a multiple of 3
2 this is not a multiple of 3
3
4 this is not a multiple of 3
5 this is not a multiple of 3
6
7 this is not a multiple of 3
8 this is not a multiple of 3
9
10 this is not a multiple of 3
11 this is not a multiple of 3
12
13 this is not a multiple of 3
14 this is not a multiple of 3
15
16 this is not a multiple of 3
17 this is not a multiple of 3
18
19 this is not a multiple of 3
20 this is not a multiple of 3

## Lists

A `list` is a __collection__ of items that are _ordered_ and _changeable_.

__Lists__ are defined by enclosing items in _square brackets_ [ ] and separating them with commas.

__Lists__ can contain elements of _different data types_, such as integers, strings, or even other lists.

__Lists__ in Python are _mutable_, meaning that you can modify the elements of a list after it is created.

In [7]:
list_elements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# adding using append
list_elements.append('End')
print("List after append:", list_elements)


# adding using insert
list_b = list_elements
list_b.insert(0, False)
print("List after insert:", list_elements)

List after append: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'End']
List after insert: [False, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'End']

In [9]:
# removing with remove
list_elements.remove("End")
print("List after remove:", list_elements)

# removing with pop 
list_elements.pop()
print("List after pop:", list_elements)

# removing with pop by index
list_elements.pop(0)
print("List after pop by index:", list_elements)

List after remove: [False, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List after pop: [False, 1, 2, 3, 4, 5, 6, 7, 8, 9]
List after pop by index: [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
# a list of lists
matrix = [[0, 1, 2, 3], [4, 5, 6], [7, 8, 9, 10, 11]]

# conditionals (positive) with lists
if [4, 5, 6] in matrix:
    print("El elemento [4, 5, 6] está.")

# conditionals (negative) with lists
if [1, 2, 3] not in matrix:
    print("El elemento [1, 2, 3] no está.")

print('-'*50)
# traversing the list
for item in matrix:
    print(item)

El elemento [4, 5, 6] está.
El elemento [1, 2, 3] no está.
--------------------------------------------------
[0, 1, 2, 3]
[4, 5, 6]
[7, 8, 9, 10, 11]

In [15]:
print(matrix[2])
matrix[1] = "Otra cosa"
print(matrix)

[7, 8, 9, 10, 11]
[[0, 1, 2, 3], 'Otra cosa', [7, 8, 9, 10, 11]]

## Dictionaries

__Dictionaries__ are a _built-in data structure_ in Python that allow you to store and retrieve data using __key-value pairs__.

A _dictionary_ (`dict`) is created using _curly braces_ {} and populated with key-value pairs.
The __keys__ could be __strings__, numbers or tuples, and the __values__ can be of _any data type_.
The __dictionary__ is then accessed using the _keys_ to __retrieve__ the corresponding _values_.

In [18]:
from pprint import pprint

# a simple dictionary
my_dict = {'a': 'Hola', 'b': 3, 'd': 4.5, 'c': True}

pprint(my_dict)

# adding a new key
my_dict['new_key'] = 'UD'
print("-"*20)
pprint(my_dict)

# removing a key
del my_dict['d']
print("-"*20)
pprint(my_dict)

{'a': 'Hola', 'b': 3, 'c': True, 'd': 4.5}
--------------------
{'a': 'Hola', 'b': 3, 'c': True, 'd': 4.5, 'new_key': 'UD'}
--------------------
{'a': 'Hola', 'b': 3, 'c': True, 'new_key': 'UD'}

In [19]:
# a dictionary of dictionaries
new_dict = {
    'pepita': {
        'grades': [3.5, 4.2],
        'phone': '+57 344564567',
        'alternative_phone': '+57 60193959593'
    }, 
    'pepito': {
        'grades': [2.5, 4.0, 3.8]
    }
}
pprint(new_dict)

# a list of dictionaries
new_list = [
    {
        'name': 'Pepita',
        'grades': [3.5, 4.2],
        'phone': '+57 344564567',
        'alternative_phone': '+57 60193959593'
    }, 
    {
        'name': 'Pepito',
        'grades': [2.5, 4.0, 3.8]
    }
]
print('-'*20)
pprint(new_list)

{'pepita': {'alternative_phone': '+57 60193959593',
            'grades': [3.5, 4.2],
            'phone': '+57 344564567'},
 'pepito': {'grades': [2.5, 4.0, 3.8]}}
--------------------
[{'alternative_phone': '+57 60193959593',
  'grades': [3.5, 4.2],
  'name': 'Pepita',
  'phone': '+57 344564567'},
 {'grades': [2.5, 4.0, 3.8], 'name': 'Pepito'}]

In [20]:
pprint(new_dict['pepita']['phone'])

'+57 344564567'

In [21]:
pprint(new_list[1])

{'grades': [2.5, 4.0, 3.8], 'name': 'Pepito'}

In [22]:
# reading a JSON in python into a dictionary
import json

with open('example.json', 'r', encoding='utf-8') as file:
    my_dict = json.load(file)

pprint(my_dict)

{'widget': {'debug': 'on',
            'image': {'alignment': 'center',
                      'hOffset': 250,
                      'name': 'sun1',
                      'src': 'Images/Sun.png',
                      'vOffset': 250},
            'text': {'alignment': 'center',
                     'data': 'Click Here',
                     'hOffset': 250,
                     'name': 'text1',
                     'onMouseUp': 'sun1.opacity = (sun1.opacity / 100) * 90;',
                     'size': 36,
                     'style': 'bold',
                     'vOffset': 100},
            'window': {'height': 500,
                       'name': 'main_window',
                       'title': 'Sample Konfabulator Widget',
                       'width': 500}}}

In [26]:
# getting keys
print("Getting keys from the dictionary:\n", my_dict['widget'].keys())

# getting values

print("Getting values from the dictionary:\n", my_dict['widget'].values())

# traversal with a loop
print('-'*10)
for key, value in my_dict['widget'].items():
    print(f'Key: {key} ---> {value}')

Getting keys from the dictionary:
 dict_keys(['debug', 'window', 'image', 'text'])
Getting values from the dictionary:
 dict_values(['on', {'title': 'Sample Konfabulator Widget', 'name': 'main_window', 'width': 500, 'height': 500}, {'src': 'Images/Sun.png', 'name': 'sun1', 'hOffset': 250, 'vOffset': 250, 'alignment': 'center'}, {'data': 'Click Here', 'size': 36, 'style': 'bold', 'name': 'text1', 'hOffset': 250, 'vOffset': 100, 'alignment': 'center', 'onMouseUp': 'sun1.opacity = (sun1.opacity / 100) * 90;'}])
----------
Key: debug ---> on
Key: window ---> {'title': 'Sample Konfabulator Widget', 'name': 'main_window', 'width': 500, 'height': 500}
Key: image ---> {'src': 'Images/Sun.png', 'name': 'sun1', 'hOffset': 250, 'vOffset': 250, 'alignment': 'center'}
Key: text ---> {'data': 'Click Here', 'size': 36, 'style': 'bold', 'name': 'text1', 'hOffset': 250, 'vOffset': 100, 'alignment': 'center', 'onMouseUp': 'sun1.opacity = (sun1.opacity / 100) * 90;'}

## Sets

__Sets__ are _unordered collections_ of _unique elements_. They are commonly used to perform mathematical __set operations__ such as _union_, _intersection_, and _difference_.

To use __sets__ in _Python_, you can create a set by enclosing comma-separated elements within _curly braces_ {}. You can also use the `set()` function to create a __set__ _from_ an _iterable object_.

Note that sets __do not allow__ _duplicate_ elements, so any duplicate elements will be _automatically removed_.

In [1]:
# creating a set
numbers = {1, 2, 3, 4, 5, 2, 3, 4, 2, 1, 2, 3, 5, 7, 6, 4, 3, 2, 3, 2}
print("Creating a set:\n", numbers)

# creating a set from a list
my_list = [1, 2, 3, 4, 5, 2, 3, 4, 2, 1, 2, 3, 5, 7, 6, 4, 3, 2, 3, 2]
my_set = set(my_list)
print("Creating a set from a list:\n", my_set)

Creating a set:
 {1, 2, 3, 4, 5, 6, 7}
Creating a set from a list:
 {1, 2, 3, 4, 5, 6, 7}

In [2]:
# union
numbers_1 = {1, 2, 3, 4}
numbers_2 = {4, 5, 6, 7}
print("Union of two sets:\n", numbers_1.union(numbers_2))

# intersection
print("Intersection of two sets:\n", numbers_1.intersection(numbers_2))

# difference
print("Difference of two sets:\n", numbers_1.difference(numbers_2))

# symmetric difference
print("Symmetric difference of two sets:\n", numbers_1.symmetric_difference(numbers_2))

Union of two sets:
 {1, 2, 3, 4, 5, 6, 7}
Intersection of two sets:
 {4}
Difference of two sets:
 {1, 2, 3}
Symmetric difference of two sets:
 {1, 2, 3, 5, 6, 7}

## Tuples

__Tuples__ are _immutable sequences_, and similar to _lists_, that can _store multiple items_.

They are defined using _parentheses_ and can contain elements of _different data types_.

Tuples are commonly used to __group related data__ together and can be accessed using _indexing_.

Unlike _lists_, tuples __cannot__ be _modified_ once created, making them useful for storing data that _should not be changed_.

In [3]:
# tuple of different data types
my_tuple = (2, 5.2, False)
print("Tuple of different data types:\n", )

# accessing by index
print("First element:", my_tuple[0])
print("Second element:", my_tuple[1])
print("Third element:", my_tuple[2])

Tuple of different data types:

First element: 2
Second element: 5.2
Third element: False

In [5]:
print("Datatype", type(my_tuple))
my_tuple[1] = "Hola"

Datatype <class 'tuple'>

TypeError: 'tuple' object does not support item assignment

In [6]:
# create a tuple from a list
my_tuple_1 = tuple(my_list)
print("Tuple created from list:", my_tuple_1)

# traversal with a loop and with a conditional
for item in my_tuple_1:
    print(item)

Tuple created from list: (1, 2, 3, 4, 5, 2, 3, 4, 2, 1, 2, 3, 5, 7, 6, 4, 3, 2, 3, 2)
1
2
3
4
5
2
3
4
2
1
2
3
5
7
6
4
3
2
3
2

In [8]:
print(id(my_list))
print(id(my_tuple_1))

tuple_2 = my_tuple_1
print(id(tuple_2))

136139571862528
136139550990112
136139550990112

## List Comprehensions

__List comprehensions__ provide a concise way to _create lists_ based on existing lists or other _iterable objects_. It allows you to transform and filter elements from the original iterable in a _single line of code_.

The general syntax of a list comprehension is:
`[expression for item in iterable if condition]`

- `expression` is the value or transformation applied to each item in the iterable.
- `item` is the variable that represents each element in the iterable.
- `iterable` is the original list or other iterable object.
- `condition` (optional) is a filter that determines whether an item should be included in the new list.

__List comprehensions__ are often used as a more readable and concise alternative to traditional for loops when creating _new lists_. They can be used to perform __operations__ such as _filtering_, _mapping_, and _transforming elements_.

_Python_ that can help _simplify code_ and make it more expressive.

In [10]:
# power of 2 since range
power_2 = [a**2 for a in range(5, 11)]
print("Power of 2 since range:\n", power_2, type(power_2))

# increase 1 to elements of a list
list_increased = [x+1 for x in power_2]
print("Increased elements of the list:\n", list_increased)

# filtering even numbers of a list
even = [i for i in list_increased if i % 2 == 0]
print("Filtered even numbers:\n", even)

# filtering names with a 'e'
names = ['ana', 'bob', 'evelyn', 'leyla']
print("Filtered names with 'e':\n", [name for name in names if 'e' in name])

Power of 2 since range:
 [25, 36, 49, 64, 81, 100] <class 'list'>
Increased elements of the list:
 [26, 37, 50, 65, 82, 101]
Filtered even numbers:
 [26, 50, 82]
Filtered names with 'e':
 ['evelyn', 'leyla']

In [13]:
students = [
    ('Pepita', 4.5, 3.8),
    ('Pepito', 3.6, 4.2),
    ('Sutanito', 4.2, 4.5)
]

students_avg = [(student[0], round((student[1] + student[2])/2, 3)) for student in students]
print(students_avg)

[('Pepita', 4.15), ('Pepito', 3.9), ('Sutanito', 4.35)]

## Functions

A __function__ in _Python_ is a block of organized, _reusable code_ that is used to perform a _single_, related _action_. __Functions__ provide better _modularity_ for your application and a high degree of _code reusing_. They are defined using the `def` _keyword_, can accept parameters, and can return results.

### Built-In Functions

A __built-in function__ in _Python_ is a _function_ that is pre-defined and available for use _without_ the need for `import` or definition by the user. These functions are an _integral part_ of the _Python_ language and provide basic functionality, such as converting types, performing mathematical calculations, and interacting with the core parts of the language.

### Variadic Functions

A __variadic function__ in _Python_ is a _function_ that can accept an arbitrary number of arguments. This allows the function to be _flexible_ in the number of values it processes. __Variadic functions__ are defined using the `*args` syntax for _positional_ arguments and `**kwargs` for _keyword_ arguments, enabling them to handle a varying amount of input data gracefully.

In [14]:
# function with no return
def function_1(case: bool) -> None:
    """This is an example of my first python function.
    
    Args:
        case(bool): The case to define which one impression made

    Returns:
        None
    """
    if case:
        print("Positive")
    else:
        print("Negative")

print("Function with no return - positive case:\n", function_1(True))
print("Function with no return - negative case:\n", function_1(False))

Positive
Function with no return - positive case:
 None
Negative
Function with no return - negative case:
 None

In [15]:
# function returning a tuple
def even() -> tuple:
    """This function returns even numbers from 2 to 10"""
    return 2, 4, 6, 8, 10
print("Function returning a tuple:\n", even())

Function returning a tuple:
 (2, 4, 6, 8, 10)

In [19]:
# function with variable parameters in a tuple
def print_tuple(data: tuple):
    for d in data:
        print(d, end='---')
    print("")

print("Function with variable parameters in a tuple:\n", print_tuple(('Pepito', 'Ingenieria de Sistemas', "UD", [4.5, 2.3])))

Pepito---Ingenieria de Sistemas---UD---[4.5, 2.3]---
Function with variable parameters in a tuple:
 None

In [8]:
# function with variable parameters in a dictionary

def function_dict(info: dict):
    if 'a' in info:
        print("Mandatory 'a' parameter is good.")
    else:
        raise ValueError("'a' key is mandatory")
    for k, v in info.items():
        print(f'key: {k} -> {v}')

my_dict = {"a": 1, "b": 2, "c": 3}
print("Function with variable parameters in a dictionary:\n", function_dict(my_dict))

Mandatory 'a' parameter is good.
key: a -> 1
key: b -> 2
key: c -> 3
Function with variable parameters in a dictionary:
 None

In [10]:
# recursive function
def factorial(n: int) -> int:
    if n <= 1:
        return 1
    else:
        return factorial(n - 1) * n

print("Recursive function - factorial of 5:\n", factorial(5))

Recursive function - factorial of 5:
 120

## Iterators

__Iterators__ are objects that allow iteration over a _collection of elements_. They provide a way to access the elements of a collection _one by one_, without the need to know the underlying structure of the collection.

In _Python_, __iterators__ are implemented using the `iter()` and `next()` methods. When there are no more elements to return, the `next__()` method raises the `StopIteration` _exception_.

__Iterators__ are commonly used in _for loops_ to iterate over elements in a sequence, such as _lists_, _tuples_, or _strings_.

### Map Function

The `map` _function_ in _Python_ applies a given function to each item of an iterable (like a list, tuple, etc.) and returns a __map object__ (which is an _iterator_) of the results. This is often used to perform _some operation_ on a collection of items and _generate a new collection_ containing the results.

### Filter Function 

The `filter` _function_ in _Python_ takes a function and an iterable as arguments and constructs an iterator from those elements of the iterable for which the function _returns_ __true__. Essentially, it filters out the elements in a collection, only _keeping those that satisfy a specific condition_.

In [16]:
# change a list of numbers in strings formats and apply power of 4
def change(number: str) -> int:
    return int(number) ** 4

numbers = input('Ingrese numeros separados por espacio:').split(' ')
print("Números:", numbers)
conv_numbers = list(map(change, numbers))

print("List of numbers in string format with power of 4:\n", conv_numbers)

Números: ['1', '2', '3', '4']
List of numbers in string format with power of 4:
 [1, 16, 81, 256]

In [17]:
# change a list of numbers in strings formats and apply power of 4 [Option 2]
numbers = input("Ingrese:").split(' ')
conv_numbers_2 = [n ** 4 for n in list(map(int, numbers))]

print("List of numbers in string format with power of 4:\n", conv_numbers_2)

List of numbers in string format with power of 4:
 [256, 1296, 81, 16]

In [20]:
# filter a list a dictionaries
def validate(student: dict):
    return student['grade'] < 3.0

students = [
    {
        'name': "Pepita", 
        'grade': 2.5
    },
    {
        'name': "Pepito", 
        'grade': 2.9
    },
    {
        'name': "Sutanita", 
        'grade': 3.5
    },
    {
        'name': "Sutanito", 
        'grade': 4.0
    }
]

print("Filter a list of dictionaries:\n", list(filter(validate, students)))

Filter a list of dictionaries:
 [{'name': 'Pepita', 'grade': 2.5}, {'name': 'Pepito', 'grade': 2.9}]

## Lambda Functions

A __lambda function__ in _Python_ is a small _anonymous function_ that can take any number of arguments but can only have _one expression_. It is defined using the `lambda` keyword, followed by a comma-separated list of parameters, a colon, and the expression to be evaluated. __Lambda functions__ are commonly used when a small function is needed for a _short period of time_ and it is not necessary to define a named function. They are often used in combination with higher-order functions like `map()`, `filter()`, and `reduce()`.

In [ ]:
# lambda function in a variable
fun = lambda x: x**3
result = fun(4)
print("Example 1:", result)

# lambdas function of two parameters in a variable
fun = lambda x_1, x_2: x_1 + x_2
result = fun(4, 5)
print("Example 2:", result)

# sort a list of tuples by the second item
pairs = [(1, 2), (3, 1), (5, 8), (7, 4), (9, 5)]
pairs.sort(key = lambda x:x[1])
print("Example 3:", pairs)

# filter a list to include multiple of 3
filtered = list(filter(lambda x: x % 3 == 0, list(range(20))))
print("Example 4:", filtered)

# create a new list with the cube of each number
cube = list(map(lambda x: x ** 3,list(range(10))))
print("Example 5:", cube)

# sort a list of strings based on length
strings = ["hello", "world", "python", "is", "awesome"]
strings.sort(key=lambda s: len(s))
print("Example 6:", strings)

Example 1: 64
Example 2: 9
Example 3: [(1, 2), (3, 1), (5, 8), (7, 4), (9, 5)]
Example 4: [0, 3, 6, 9, 12, 15, 18]
Example 5: [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
Example 6: ['is', 'hello', 'world', 'python', 'awesome']

In [ ]:
# Java-C: cond? T:F

def validation(grade):
    return "Approve" if grade >= 3.0 else "Reject"

In [ ]:
students_status = list(
    map(
        lambda student: (
            f"{student['name']} Approve"
            if student["grade"] >= 3.0
            else f"{student['name']} Reject"
        ),
        students,
    )
)
print(students_status)

['Pepita Reject', 'Pepito Reject', 'Sutanita Approve', 'Sutanito Approve']

## Classes

 A `class` is a blueprint for creating objects in Python. It defines a set of _attributes_ and _methods_ that the objects of the class will have.

In [32]:
# create an abstract class
from abc import ABC, abstractmethod
class MyAbstractCalculator(ABC):

    def __init__(self):
        print("Bienvenido a la calculadora UD")

    @abstractmethod
    def sum(self, x, y):
        pass

    @abstractmethod
    def multiplication(self, x, y):
        pass

In [34]:
# create a concrete class
class MyCalculator(MyAbstractCalculator):
    def sum(self, x, y):
        return x + y
    
    def multiplication(self, x, y):
        return x * y

In [35]:
# instanciate a concrete object
calc = MyCalculator()
print(calc.sum(3, 5))

Bienvenido a la calculadora UD
8

# Numpy

__Numpy__ is a _Python package_ that stands for ___Numerical Python___. It is a _library_ for the _Python_ programming language, adding support for large, _multi-dimensional arrays_ and _matrices_, along with a _large collection_ of high-level mathematical functions to operate on these _arrays_.

__Numpy__ provides a powerful _N-dimensional_ array object, useful for performing mathematical and logical operations on arrays. It also has _functions_ for working in domain of _linear algebra_, _Fourier transform_, and _matrices_.

By importing `numpy as np`, we can access all the functions and methods provided by the _numpy_ package using the `np` alias.

In [2]:
import numpy as np

# create an array
array = np.array([3, 6, 7, 2, 1])
print("Array 1:", array)

# create an array with range
print("Array 2:", np.arange(1,100,2))

# create an array with linspace
print("Array 3:", np.linspace(0, 100, 150))

# create a matrix of zeros
matrix = np.zeros((30, 50))
print("Matrix:", matrix)

Array 1: [3 6 7 2 1]
Array 2: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
Array 3: [  0.           0.67114094   1.34228188   2.01342282   2.68456376
   3.3557047    4.02684564   4.69798658   5.36912752   6.04026846
   6.7114094    7.38255034   8.05369128   8.72483221   9.39597315
  10.06711409  10.73825503  11.40939597  12.08053691  12.75167785
  13.42281879  14.09395973  14.76510067  15.43624161  16.10738255
  16.77852349  17.44966443  18.12080537  18.79194631  19.46308725
  20.13422819  20.80536913  21.47651007  22.14765101  22.81879195
  23.48993289  24.16107383  24.83221477  25.5033557   26.17449664
  26.84563758  27.51677852  28.18791946  28.8590604   29.53020134
  30.20134228  30.87248322  31.54362416  32.2147651   32.88590604
  33.55704698  34.22818792  34.89932886  35.5704698   36.24161074
  36.91275168  37.58389262  38.25503356  38.9261745   39.59731544
  40.26845638  40.93959732  41.61073826  42.28187919  42.95302013
  43.62416107  44.29530201  44.96644295  45.63758389  46.30872483
  46.97986577  47.65100671  48.32214765  48.99328859  49.66442953
  50.33557047  51.00671141  51.67785235  52.34899329  53.02013423
  53.69127517  54.36241611  55.03355705  55.70469799  56.37583893
  57.04697987  57.71812081  58.38926174  59.06040268  59.73154362
  60.40268456  61.0738255   61.74496644  62.41610738  63.08724832
  63.75838926  64.4295302   65.10067114  65.77181208  66.44295302
  67.11409396  67.7852349   68.45637584  69.12751678  69.79865772
  70.46979866  71.1409396   71.81208054  72.48322148  73.15436242
  73.82550336  74.4966443   75.16778523  75.83892617  76.51006711
  77.18120805  77.85234899  78.52348993  79.19463087  79.86577181
  80.53691275  81.20805369  81.87919463  82.55033557  83.22147651
  83.89261745  84.56375839  85.23489933  85.90604027  86.57718121
  87.24832215  87.91946309  88.59060403  89.26174497  89.93288591
  90.60402685  91.27516779  91.94630872  92.61744966  93.2885906
  93.95973154  94.63087248  95.30201342  95.97315436  96.6442953
  97.31543624  97.98657718  98.65771812  99.32885906 100.        ]
Matrix: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [4]:
# get shape of array
print("Array Shape:", array.shape)

# get shape of matrix
print("Matrix Shape:", matrix.shape)

# get number of dimensions of array
print("Array Dimensions:", array.ndim)

# get number of dimensions of matrix
print("Matrix Dimensions:", matrix.ndim)

Array Shape: (5,)
Matrix Shape: (30, 50)
Array Dimensions: 1
Matrix Dimensions: 2

In [7]:
# ========== descriptive statistics ========== #
data = np.random.randint(1, 101, size=5000000)
#print("Data:", data)

# get sum of array
print("Sum of array:", np.sum(data))

# get mean of array
print("Mean of array:", np.mean(data))

# get standard deviation of array
print("Standard Deviation of array:", np.std(data))

# get variance of array
print("Variance of array:", np.var(data))

# get min of array
print("Min of array:", np.min(data))

# get max of array
print("Max of array:", np.max(data))

Sum of array: 252590050
Mean of array: 50.51801
Standard Deviation of array: 28.866494709955692
Variance of array: 833.2745168399
Min of array: 1
Max of array: 100

## Linear Algebra with Numpy

_Numpy_ is a powerful _Python_ package that provides support for _linear algebra_ operations. It allows us to perform various mathematical operations on _arrays_ and _matrices_ efficiently.

With __Numpy__, we can easily solve _linear algebra_ problems such as finding solutions to systems of linear equations, calculating matrix determinants, eigenvalues, eigenvectors, and much more.

#

In [8]:
# solve a system of linear equations
equations = np.array([[2, 1], [3, 5]])
answers = np.array([1, 2])

print("Solutions:", np.linalg.solve(equations, answers))
# to solve a system of linear equations, the number of equations must equal the number of unknowns

Solutions: [0.42857143 0.14285714]

In [11]:
# get the inverse of a matrix
matrix = np.array([[1, 2], [3, 4]])
print("Inverse of Matrix:", np.linalg.inv(matrix))

# to get the inverse of a matrix, 
# the matrix must be square (number of rows = number of columns)
# the matrix must be non-singular (determinant is not zero)
# Inversa = [[d/ad-bc, -b/ad-bc], [-c/ad-bc, a/ad-bc]]

Inverse of Matrix: [[-2.   1. ]
 [ 1.5 -0.5]]

In [10]:
# get the determinant of a matrix
print("Determinant of Matrix:", np.linalg.det(matrix))

# the determinant of a matrix is a scalar value  calculated with next formula
# det(A) = ad - bc

Determinant of Matrix: -2.0000000000000004

In [4]:
# get the dot product of two arrays
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print("Dot Product:", np.dot(array_1, array_2))
# dot = 1*4 + 2*5 + 3*6

Dot Product: 32

In [5]:
# get the cross product of two arrays
print("Cross Product:", np.cross(array_1, array_2))

# cross = [2*6-3*5, 3*4-1*6, 1*5-2*4]

Cross Product: [-3  6 -3]

In [8]:
# get the eigenvalues and eigenvectors of a matrix
A = np.array([
    [2, 1], 
    [1, 2]
    ])
print("Eigenvalues:", np.linalg.eig(A)[0])
print("Eigenvectors:", np.linalg.eig(A)[1])

# the eigenvalues of a matrix are the values that satisfy the equation det(A - λI) = 0
# the eigenvectors of a matrix are the vectors that satisfy the equation A*v = λ*v

# eigenvectors are used in principal component analysis (PCA) to reduce the dimensionality of data

Eigenvalues: [3.+0.j 1.+0.j]
Eigenvectors: [[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]

## Vectorization

__Vectorization__ is a technique in computer programming that allows us to perform operations on _entire arrays or matrices_ instead of looping through each element individually. This approach leverages the power of optimized, low-level operations provided by libraries like __NumPy__.

By using _vectorized operations_, we can significantly improve the _performance_ of our code, as it takes advantage of parallel processing capabilities of modern _CPUs_. Instead of writing explicit loops, we can express our computations as _mathematical expressions_ on arrays, making our code more concise and readable.

For example, instead of iterating over each element of an array to calculate the square root, we can simply apply the `np.sqrt()` function to the _entire array_. This not only simplifies the code but also improves its efficiency.

In addition to arithmetic operations, __vectorization__ also enables us to perform logical operations, mathematical functions, and other operations on arrays and matrices. This makes it a powerful tool for _scientific computing_, _data analysis_, and _machine learning_ tasks.

Overall, __vectorization__ is a fundamental concept in array programming that allows us to write efficient and concise code by operating on entire arrays or matrices at once. It is a key technique to leverage the full potential of libraries like __NumPy__ and optimize our computations.

In [1]:
!pip install memory_profiler
import numpy as np
import memory_profiler
import time

# decorator to time a function
def time_function(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Time taken: {end - start}")
        return result
    return wrapper

# decorator to get memory usage of a function
def memory_function(func):
    def wrapper(*args, **kwargs):
        result = memory_profiler.memory_usage((func, args, kwargs))
        print(f"Memory used: {result[0]}")
        return result
    return wrapper

Requirement already satisfied: memory_profiler in /home/casierrav/.pyenv/versions/3.14.1/envs/pda_exercises/lib/python3.14/site-packages (0.61.0)
Requirement already satisfied: psutil in /home/casierrav/.pyenv/versions/3.14.1/envs/pda_exercises/lib/python3.14/site-packages (from memory_profiler) (7.2.2)

In [3]:
# calculare the square root of a matrix with vertorization
@time_function
@memory_function
def sqrt_vectorized(matrix):
    return np.sqrt(matrix)

# calculate the square root of a matrix with a loop
@time_function
@memory_function
def sqrt_loop(matrix):
    result = np.zeros_like(matrix)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i, j] = np.sqrt(matrix[i, j])
    return result

size = 1000
matrix = np.random.rand(size, size)
print("Shape:", matrix.shape)
print("Vectorized")
t = sqrt_vectorized(matrix)
print("Loop")
t = sqrt_loop(matrix)

Shape: (1000, 1000)
Vectorized
Memory used: 78.7734375
Time taken: 0.9612295627593994
Loop
Memory used: 78.56640625
Time taken: 1.2317237854003906

In [7]:
# calculate the sum of two arrays witn vectorization
@time_function
@memory_function
def sum_vectorized(array1, array2):
    return array1 + array2

# calculate the sum of two arrays with a loop
@time_function
@memory_function
def sum_loop(array1, array2):
    result = np.zeros_like(array1)
    for i in range(array1.shape[0]):
        result[i] = array1[i] + array2[i]
    return result

size = 1000000
array1 = np.random.rand(size)
array2 = np.random.rand(size)
print("Shape:", array1.shape)
print("Vectorized")
t = sum_vectorized(array1, array2)
print("Loop")
t = sum_loop(array1, array2)

Shape: (1000000,)
Vectorized
Memory used: 101.74609375
Time taken: 2.0749363899230957
Loop
Memory used: 86.61328125
Time taken: 0.8486185073852539

In [11]:
# calculate broadcasted multiplication of and array and a scalar with vectorization
@time_function
@memory_function
def broadcasted_vectorized(array, scalar):
    return array * scalar

# calculate broadcasted multiplication of and array and a scalar with a loop
@time_function
@memory_function
def broadcasted_loop(array, scalar):
    result = np.zeros_like(array)
    scalar = scalar[0]
    for i in range(array.shape[0]):
        result[i] = array[i] * scalar
    return result

size = 10000000
array = np.random.rand(size)
scalar = np.random.rand(1)
print("Shape:", array.shape)
print("Vectorized")
t = broadcasted_vectorized(array, scalar)
print("Loop")
t = broadcasted_loop(array, scalar)

Shape: (10000000,)
Vectorized
Memory used: 746.81640625
Time taken: 0.6887478828430176
Loop
Memory used: 670.51953125
Time taken: 4.036427736282349

In [12]:
# filter an array with vectorization
@time_function
@memory_function
def is_even(x):
    return x % 2 == 0

# filter an array with a loop
@time_function
@memory_function
def is_even_loop(array):
    result = []
    for x in array:
        if x % 2 == 0:
            result.append(x)
    return result

# filter an array with a lambda function
@time_function
@memory_function
def is_even_lambda(array):
    return list(filter(lambda x: x % 2 == 0, array))

size = 10000000
array = np.random.randint(0, 100, size)
print("Shape:", array.shape)
print("Vectorized")
t = is_even(array)
print("Loop")
t = is_even_loop(array)
print("Lambda")
t = is_even_lambda(array)

Shape: (10000000,)
Vectorized
Memory used: 670.77734375
Time taken: 0.550438404083252
Loop
Memory used: 671.02734375
Time taken: 3.909679651260376
Lambda
Memory used: 681.453125
Time taken: 4.731789827346802

# PANDAS

__Pandas__ is a powerful _open-source_ data manipulation and analysis library for _Python_. 

It provides data structures and functions for efficiently __handling and analyzing structured data__, such as tables or spreadsheets.

With __pandas__, you can easily _load_, _manipulate_, _analyze data_, perform _data cleaning_ and _preprocessing_ tasks, and create _visualizations_.

It is widely used in _data science_, _machine learning_, and _data analysis_ projects.

To import the pandas library and assigns it the alias 'pd', you could make `import pandas as pd`.

## The Series Data Structure

A __pandas Series__ is a _one-dimensional labeled array_ capable of holding any data type. It is similar to a _column_ in a spreadsheet or a SQL table, or a _dictionary-like_ object. It is a fundamental _data structure_ in __pandas__ library, which is widely used for data manipulation and analysis in Python.

A __pandas Series__ consists of two main components: the _data_ and the _index_. The _data_ can be of any type, such as integers, floats, strings, or even complex objects. The _index_ is a sequence of labels that uniquely identifies each element in the Series.

Some key features of pandas Series include:
- Vectorized operations: Series supports vectorized operations, allowing you to perform element-wise computations efficiently.
- Label-based indexing: You can access elements in a Series using labels instead of integer-based indexing.
- Alignment: Series automatically aligns data based on the index, making it easy to perform operations on multiple Series with different indexes.

To create a __Series__, you can pass a list, array, or dictionary-like object to the `pd.Series()` constructor. You can also specify custom index labels if needed.

In [1]:
import pandas as pd

# Create a Series object from a list of strings
list_strings = ['a', 'b', 'c', 'd', 'e']
serie_1 = pd.Series(list_strings)
print("Serie 1:\n", serie_1)

# Create a Series object from a list of numbers
list_numbers = [1, 2, 3, 4, 5]
serie_2 = pd.Series(list_numbers)
print("Serie 2:\n", serie_2)

# Create a Series object from a list of numbers with a None value
list_numbers_with_none = [1, 2, None, 4, 5]
serie_3 = pd.Series(list_numbers_with_none)
print("Serie 3:\n", serie_3)

Serie 1:
 0    a
1    b
2    c
3    d
4    e
dtype: str
Serie 2:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Serie 3:
 0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [3]:
# Create a Series object from a dictionary
dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
serie_4 = pd.Series(dict_data)
print("Serie 4:\n", serie_4)

# Get the values of the Series index
print("Serie 4 index:", serie_4.index)

Serie 4:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
Serie 4 index: Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [4]:
# Create a series object from a list of tuple pairs
list_tuples = [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]
serie_5 = pd.Series(list_tuples)
print("Serie 5:\n", serie_5)

Serie 5:
 0    (a, 1)
1    (b, 2)
2    (c, 3)
3    (d, 4)
4    (e, 5)
dtype: object

In [9]:
# Create a series object from a list as values and a list as index
list_index = ['a', 'b', 'c', 'd', 'e']
list_values = [1, 2, 3, 4, 5]
serie_6 = pd.Series(list_values, index=list_index)
print("Serie 6:\n", serie_6)

for index, value in serie_6.items():
    print(f"Index: {index}, Value: {value}")

Serie 6:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
Index: a, Value: 1
Index: b, Value: 2
Index: c, Value: 3
Index: d, Value: 4
Index: e, Value: 5

In [10]:
# Query a Series object by boolean indexing
print("Serie 6 > 2:\n", serie_6 > 2)
print("-"*10)
print( serie_6[ serie_6 > 2 ] )

Serie 6 > 2:
 a    False
b    False
c     True
d     True
e     True
dtype: bool
----------
c    3
d    4
e    5
dtype: int64

In [12]:
# Query a Series object by faccy indexing
print("Serie 6[['a', 'd', 'c]]:\n", serie_6[ ['a', 'd', 'c'] ])

Serie 6[['a', 'd', 'c]]:
 a    1
d    4
c    3
dtype: int64

In [ ]:
# Query a Series object using loc[]
print("Serie 6.loc[['e', 'b']]:\n", serie_6.loc[ ['e', 'b'] ])

Serie 6.loc[['a', 'b']]:
 e    5
b    2
dtype: int64

In [18]:
# Query a Series object using iloc[]
print("Serie 6.iloc[0:3]:\n", serie_6.iloc[0:3])
print("Serie 6.iloc[-2:]:\n", serie_6.iloc[-2:])

Serie 6.iloc[0:3]:
 a    1
b    2
c    3
dtype: int64
Serie 6.iloc[-2:]:
 d    4
e    5
dtype: int64

## The DataFrame Data Structure

A __pandas DataFrame__ is a _two-dimensional_, _labeled_ data structure in _Python_ that is commonly used for _data manipulation and analysis_. It consists of _rows_ and _columns_, similar to a table in a relational database.

The __DataFrame__ can store _heterogeneous data types_ and provides various operations and functions to perform data manipulation, filtering, grouping, and statistical analysis.

To access and manipulate the data in the __DataFrame__, you can use various _methods_ and _attributes_ provided by the __pandas__ library.

For more information on __pandas DataFrame__, refer to the [official pandas documentation](https://pandas.pydata.org/docs/reference/frame.html).

In [1]:
import pandas as pd

In [2]:
# create dataframes from lists
list_example = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
df = pd.DataFrame(list_example)
print("Dataframe from list:\n", df)
print("Dataframe shape:", df.shape)
print("Dataframe columns:", df.columns)
print("Dataframe index:", df.index)

Dataframe from list:
    0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
Dataframe shape: (3, 3)
Dataframe columns: RangeIndex(start=0, stop=3, step=1)
Dataframe index: RangeIndex(start=0, stop=3, step=1)

In [3]:
# create a dataframe from a list of dictionaries
list_dict = [{'a': 1, 'b': 2, 'd': 3}, {'a': 4, 'b': 5, 'c': 6}, {'a': 7, 'b': 8, 'c': 9}]
df = pd.DataFrame(list_dict)
print("Dataframe from list of dictionaries:\n", df)
print("Dataframe columns:", df.columns)
print("Dataframe index:", df.index)

Dataframe from list of dictionaries:
    a  b    d    c
0  1  2  3.0  NaN
1  4  5  NaN  6.0
2  7  8  NaN  9.0
Dataframe columns: Index(['a', 'b', 'd', 'c'], dtype='str')
Dataframe index: RangeIndex(start=0, stop=3, step=1)

In [2]:
# create a dataframe from a csv file
df_csv = pd.read_csv('possum.csv')
df_csv

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,100,7,other,m,1.0,89.5,56.0,81.5,36.5,66.0,46.8,14.8,23.0,27.0
100,101,7,other,m,1.0,88.6,54.7,82.5,39.0,64.4,48.0,14.0,25.0,33.0
101,102,7,other,f,6.0,92.4,55.0,89.0,38.0,63.5,45.4,13.0,25.0,30.0
102,103,7,other,m,4.0,91.5,55.2,82.5,36.5,62.9,45.9,15.4,25.0,29.0
103,104,7,other,f,3.0,93.6,59.9,89.0,40.0,67.6,46.0,14.8,28.5,33.5

In [3]:
# create a dataframe from a json file
df_json = pd.read_json('example_ii.json')
df_json

                  image_1          image_2           image_3
src        Images/Sun.png  Images/Moon.png  Images/Pluto.png
name                 sun1            moon1             pluto
hOffset               250              250               250
vOffset               250              250               250
alignment          center           center            center

In [6]:
# describe a dataframe
print("Dataframe csv describe:\n", df_csv.describe())
print("*"*10)
print("Dataframe json describe:\n", df_json.describe())

Dataframe csv describe:
              case        site         age     hdlngth      skullw    totlngth  \
count  104.000000  104.000000  102.000000  104.000000  104.000000  104.000000
mean    52.500000    3.625000    3.833333   92.602885   56.883654   87.088462
std     30.166206    2.349086    1.909244    3.573349    3.113426    4.310549
min      1.000000    1.000000    1.000000   82.500000   50.000000   75.000000
25%     26.750000    1.000000    2.250000   90.675000   54.975000   84.000000
50%     52.500000    3.000000    3.000000   92.800000   56.350000   88.000000
75%     78.250000    6.000000    5.000000   94.725000   58.100000   90.000000
max    104.000000    7.000000    9.000000  103.100000   68.600000   96.500000

            taill    footlgth    earconch         eye       chest       belly
count  104.000000  103.000000  104.000000  104.000000  104.000000  104.000000
mean    37.009615   68.459223   48.130769   15.046154   27.000000   32.586538
std      1.959518    4.395306    4.109380    1.050374    2.045597    2.761949
min     32.000000   60.300000   40.300000   12.800000   22.000000   25.000000
25%     35.875000   64.600000   44.800000   14.400000   25.500000   31.000000
50%     37.000000   68.000000   46.800000   14.900000   27.000000   32.500000
75%     38.000000   72.500000   52.000000   15.725000   28.000000   34.125000
max     43.000000   77.900000   56.200000   17.800000   32.000000   40.000000
**********
Dataframe json describe:
         image_1  image_2  image_3
count         5        5        5
unique        4        4        4
top         250      250      250
freq          2        2        2

In [7]:
# get information about a dataframe
print("Dataframe csv info:\n", df_csv.info())
print("="*50)
print("Dataframe json info:\n", df_json.info())

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   case      104 non-null    int64
 1   site      104 non-null    int64
 2   Pop       104 non-null    str
 3   sex       104 non-null    str
 4   age       102 non-null    float64
 5   hdlngth   104 non-null    float64
 6   skullw    104 non-null    float64
 7   totlngth  104 non-null    float64
 8   taill     104 non-null    float64
 9   footlgth  103 non-null    float64
 10  earconch  104 non-null    float64
 11  eye       104 non-null    float64
 12  chest     104 non-null    float64
 13  belly     104 non-null    float64
dtypes: float64(10), int64(2), str(2)
memory usage: 11.5 KB
Dataframe csv info:
 None
==================================================
<class 'pandas.DataFrame'>
Index: 5 entries, src to alignment
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   image_1  5 non-null      object
 1   image_2  5 non-null      object
 2   image_3  5 non-null      object
dtypes: object(3)
memory usage: 160.0+ bytes
Dataframe json info:
 None

In [10]:
df

   a  b    d    c
0  1  2  3.0  NaN
1  4  5  NaN  6.0
2  7  8  NaN  9.0

In [12]:
# indexes and columns
df_changed_index = df.copy()
df_changed_index.index = ['uno', 'dos', 'tres']
print("Dataframe csv changed index:\n", df_changed_index)
print("*"*50)
df_changed_index.columns = ['col_1', 'col_2', 'col_3', 'col_4']
print("Dataframe csv changed index columns:\n", df_changed_index.columns)
print("Dataframe csv changed index index:\n", df_changed_index.index)
df_changed_index

Dataframe csv changed index:
       a  b    d    c
uno   1  2  3.0  NaN
dos   4  5  NaN  6.0
tres  7  8  NaN  9.0
**************************************************
Dataframe csv changed index columns:
 Index(['col_1', 'col_2', 'col_3', 'col_4'], dtype='str')
Dataframe csv changed index index:
 Index(['uno', 'dos', 'tres'], dtype='str')

      col_1  col_2  col_3  col_4
uno       1      2    3.0    NaN
dos       4      5    NaN    6.0
tres      7      8    NaN    9.0

In [13]:
df_changed_index = df_changed_index.reset_index()
df_changed_index

  index  col_1  col_2  col_3  col_4
0   uno      1      2    3.0    NaN
1   dos      4      5    NaN    6.0
2  tres      7      8    NaN    9.0

In [14]:
df_changed_index = df_changed_index.set_index('col_4')
df_changed_index

      index  col_1  col_2  col_3
col_4
NaN     uno      1      2    3.0
6.0     dos      4      5    NaN
9.0    tres      7      8    NaN

In [15]:
# rename columns
df_renamed = df_changed_index.rename(columns={'index':'id', 'col_2':'grades'})
df_renamed.head()

         id  col_1  grades  col_3
col_4
NaN     uno      1       2    3.0
6.0     dos      4       5    NaN
9.0    tres      7       8    NaN

## Using Datetime into Pandas

In [8]:
# converting a column to datetime with to_datetime()
data_df = pd.read_csv('bikes.csv')
print("DataFrame Info:\n", data_df.info())

data_df = data_df.rename(columns={'datetime': 'date'})
data_df['date'] = pd.to_datetime( data_df['date'] )
print("Sales dataframe with Date column as datetime:\n", data_df.info())

# Feature Engineering
data_df['date_2'] = data_df['date'].dt.strftime("%Y-%m")
data_df['date_3'] = data_df['date'].dt.strftime("%Y-%m-%d")
data_df['date_4'] = data_df['date'].dt.strftime("%Y-%B-%d")
data_df['hour'] = data_df['date'].dt.strftime("%H:%M")
print("Replace date as String:\n", data_df.info())
data_df

<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  str
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), str(1)
memory usage: 1020.7 KB
DataFrame Info:
 None
<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10886 non-null  datetime64[us]
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(8)
memory usage: 1020.7 KB
Sales dataframe with Date column as datetime:
 None
<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10886 non-null  datetime64[us]
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
 12  date_2      10886 non-null  str
 13  date_3      10886 non-null  str
 14  date_4      10886 non-null  str
 15  hour        10886 non-null  str
dtypes: datetime64[us](1), float64(3), int64(8), str(4)
memory usage: 1.3 MB
Replace date as String:
 None

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011-01,2011-01-01,2011-January-01,00:00
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,2011-01,2011-01-01,2011-January-01,01:00
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011-01,2011-01-01,2011-January-01,02:00
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,2011-01,2011-01-01,2011-January-01,03:00
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011-01,2011-01-01,2011-January-01,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336,2012-12,2012-12-19,2012-December-19,19:00
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241,2012-12,2012-12-19,2012-December-19,20:00
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168,2012-12,2012-12-19,2012-December-19,21:00
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129,2012-12,2012-12-19,2012-December-19,22:00
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88,2012-12,2012-12-19,2012-December-19,23:00

In [22]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10886 non-null  datetime64[us]
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
 12  date_2      10886 non-null  str
 13  date_3      10886 non-null  str
 14  date_4      10886 non-null  str
 15  hour        10886 non-null  str
dtypes: datetime64[us](1), float64(3), int64(8), str(4)
memory usage: 1.3 MB

In [5]:
# converting a column from datetime to a timestamp with timestamp(), then converting it to int64
data_df['unix'] = data_df['date'].apply(lambda x: x.timestamp()).astype('int64')
data_df.head()

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour,unix
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011-01,2011-01-01,2011-January-01,00:00,1293840000
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40,2011-01,2011-01-01,2011-January-01,01:00,1293843600
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2011-01,2011-01-01,2011-January-01,02:00,1293847200
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13,2011-01,2011-01-01,2011-January-01,03:00,1293850800
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1,2011-01,2011-01-01,2011-January-01,04:00,1293854400

In [21]:
# descriptive statistics of a dataframe
print(data_df.describe())

                             date        season       holiday    workingday  \
count                       10886  10886.000000  10886.000000  10886.000000
mean   2011-12-27 05:56:22.399412      2.506614      0.028569      0.680875
min           2011-01-01 00:00:00      1.000000      0.000000      0.000000
25%           2011-07-02 07:15:00      2.000000      0.000000      0.000000
50%           2012-01-01 20:30:00      3.000000      0.000000      1.000000
75%           2012-07-01 12:45:00      4.000000      0.000000      1.000000
max           2012-12-19 23:00:00      4.000000      1.000000      1.000000
std                           NaN      1.116174      0.166599      0.466159

            weather         temp         atemp      humidity     windspeed  \
count  10886.000000  10886.00000  10886.000000  10886.000000  10886.000000
mean       1.418427     20.23086     23.655084     61.886460     12.799395
min        1.000000      0.82000      0.760000      0.000000      0.000000
25%        1.000000     13.94000     16.665000     47.000000      7.001500
50%        1.000000     20.50000     24.240000     62.000000     12.998000
75%        2.000000     26.24000     31.060000     77.000000     16.997900
max        4.000000     41.00000     45.455000    100.000000     56.996900
std        0.633839      7.79159      8.474601     19.245033      8.164537

             casual    registered         count
count  10886.000000  10886.000000  10886.000000
mean      36.021955    155.552177    191.574132
min        0.000000      0.000000      1.000000
25%        4.000000     36.000000     42.000000
50%       17.000000    118.000000    145.000000
75%       49.000000    222.000000    284.000000
max      367.000000    886.000000    977.000000
std       49.960477    151.039033    181.144454

In [42]:
%%timeit -n 100
import numpy as np

print(np.round(np.sum(data_df['temp']), 3))

220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
The slowest run took 5.78 times longer than the fastest. This could mean that an intermediate result is being cached.
504 μs ± 391 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [43]:
%%timeit -n 100
import numpy as np
total = 0
for item in data_df['temp']:
    total += item
print(np.round(total, 3))

220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
220233.14
3.47 ms ± 250 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

## Queries and Transformations

In [7]:
data_df

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour,unix
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011-01,2011-01-01,2011-January-01,00:00,1293840000
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,2011-01,2011-01-01,2011-January-01,01:00,1293843600
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011-01,2011-01-01,2011-January-01,02:00,1293847200
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,2011-01,2011-01-01,2011-January-01,03:00,1293850800
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011-01,2011-01-01,2011-January-01,04:00,1293854400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336,2012-12,2012-12-19,2012-December-19,19:00,1355943600
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241,2012-12,2012-12-19,2012-December-19,20:00,1355947200
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168,2012-12,2012-12-19,2012-December-19,21:00,1355950800
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129,2012-12,2012-12-19,2012-December-19,22:00,1355954400
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88,2012-12,2012-12-19,2012-December-19,23:00,1355958000

In [10]:
# drop a column
print(data_df.columns)
data_copy_df = data_df.copy().drop(columns=["date"]) 
data_copy_df.head()

Index(['date', 'season', 'holiday', 'workingday', 'weather', 'temp', 'atemp',
       'humidity', 'windspeed', 'casual', 'registered', 'count', 'date_2',
       'date_3', 'date_4', 'hour'],
      dtype='str')

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
0,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011-01,2011-01-01,2011-January-01,00:00
1,1,0,0,1,9.02,13.635,80,0.0,8,32,40,2011-01,2011-01-01,2011-January-01,01:00
2,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2011-01,2011-01-01,2011-January-01,02:00
3,1,0,0,1,9.84,14.395,75,0.0,3,10,13,2011-01,2011-01-01,2011-January-01,03:00
4,1,0,0,1,9.84,14.395,75,0.0,0,1,1,2011-01,2011-01-01,2011-January-01,04:00

In [33]:
# drop a row

data_copy_df = data_copy_df.drop(index=[1, 3])
data_copy_df.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
0,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011-01,2011-01-01,2011-January-01,00:00
2,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011-01,2011-01-01,2011-January-01,02:00
4,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011-01,2011-01-01,2011-January-01,04:00
5,1,0,0,2,9.84,12.880,75,6.0032,0,1,1,2011-01,2011-01-01,2011-January-01,05:00
6,1,0,0,1,9.02,13.635,80,0.0000,2,0,2,2011-01,2011-01-01,2011-January-01,06:00

In [11]:
print(data_df['weather'].unique())

[1 2 3 4]

In [ ]:
# query a dataframe by column
"""
SELECT *
FROM data_df
WHERE weather != 1 
  AND humiduty > 72; 
"""
data_df[ (data_df['weather'] != 1) & (data_df['humidity'] > 72) ]

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.88,75,6.0032,0,1,1,2011-01,2011-01-01,2011-January-01,05:00
15,2011-01-01 15:00:00,1,0,0,2,18.04,21.97,77,19.9995,40,70,110,2011-01,2011-01-01,2011-January-01,15:00
16,2011-01-01 16:00:00,1,0,0,2,17.22,21.21,82,19.9995,41,52,93,2011-01,2011-01-01,2011-January-01,16:00
17,2011-01-01 17:00:00,1,0,0,2,18.04,21.97,82,19.0012,15,52,67,2011-01,2011-01-01,2011-January-01,17:00
18,2011-01-01 18:00:00,1,0,0,3,17.22,21.21,88,16.9979,9,26,35,2011-01,2011-01-01,2011-January-01,18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,2012-12-17 22:00:00,4,0,1,2,17.22,21.21,94,8.9981,5,49,54,2012-12,2012-12-17,2012-December-17,22:00
10837,2012-12-17 23:00:00,4,0,1,3,17.22,21.21,94,15.0013,6,41,47,2012-12,2012-12-17,2012-December-17,23:00
10838,2012-12-18 00:00:00,4,0,1,2,18.04,21.97,94,8.9981,0,18,18,2012-12,2012-12-18,2012-December-18,00:00
10839,2012-12-18 01:00:00,4,0,1,2,18.04,21.97,94,8.9981,0,15,15,2012-12,2012-12-18,2012-December-18,01:00
10840,2012-12-18 02:00:00,4,0,1,2,18.04,21.97,88,15.0013,2,5,7,2012-12,2012-12-18,2012-December-18,02:00

In [25]:
# last month
last_month = pd.Timestamp.today().to_period('M') - 1
print(last_month)
data_df[ data_df['date'].dt.to_period('M') == last_month]

2026-09

Empty DataFrame
Columns: [date, season, holiday, workingday, weather, temp, atemp, humidity, windspeed, casual, registered, count, date_2, date_3, date_4, hour]
Index: []

In [ ]:
reference_date = pd.Timestamp('2012-12-01')
last_days_df = data_df[ (data_df['date'] >= reference_date) & 
                       (data_df['date'] < reference_date+pd.Timedelta(days=15)) ]
last_days_df

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
10430,2012-12-01 00:00:00,4,0,0,1,10.66,15.150,81,0.0000,9,99,108,2012-12,2012-12-01,2012-December-01,00:00
10431,2012-12-01 01:00:00,4,0,0,1,10.66,15.150,81,0.0000,5,64,69,2012-12,2012-12-01,2012-December-01,01:00
10432,2012-12-01 02:00:00,4,0,0,2,10.66,15.150,81,0.0000,3,47,50,2012-12,2012-12-01,2012-December-01,02:00
10433,2012-12-01 03:00:00,4,0,0,2,10.66,13.635,81,8.9981,1,14,15,2012-12,2012-12-01,2012-December-01,03:00
10434,2012-12-01 04:00:00,4,0,0,1,10.66,14.395,81,6.0032,0,5,5,2012-12,2012-12-01,2012-December-01,04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10785,2012-12-15 19:00:00,4,0,0,1,14.76,17.425,62,8.9981,32,225,257,2012-12,2012-12-15,2012-December-15,19:00
10786,2012-12-15 20:00:00,4,0,0,2,14.76,17.425,57,12.9980,23,178,201,2012-12,2012-12-15,2012-December-15,20:00
10787,2012-12-15 21:00:00,4,0,0,1,14.76,17.425,62,8.9981,15,169,184,2012-12,2012-12-15,2012-December-15,21:00
10788,2012-12-15 22:00:00,4,0,0,1,14.76,17.425,62,12.9980,22,134,156,2012-12,2012-12-15,2012-December-15,22:00
10789,2012-12-15 23:00:00,4,0,0,2,14.76,17.425,62,8.9981,11,108,119,2012-12,2012-12-15,2012-December-15,23:00

In [40]:
# query a dataframe by row with loc
data_copy_df.loc[2]

season                      1
holiday                     0
workingday                  0
weather                     1
temp                     9.02
atemp                  13.635
humidity                   80
windspeed                 0.0
casual                      5
registered                 27
count                      32
date_2                2011-01
date_3             2011-01-01
date_4        2011-January-01
hour                    02:00
Name: 2, dtype: object

In [41]:
# query a dataframe by row with iloc
data_copy_df.iloc[1]

season                      1
holiday                     0
workingday                  0
weather                     1
temp                     9.02
atemp                  13.635
humidity                   80
windspeed                 0.0
casual                      5
registered                 27
count                      32
date_2                2011-01
date_3             2011-01-01
date_4        2011-January-01
hour                    02:00
Name: 2, dtype: object

In [42]:
data_df.head()

,date,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,date_2,date_3,date_4,hour
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011-01,2011-01-01,2011-January-01,00:00
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40,2011-01,2011-01-01,2011-January-01,01:00
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2011-01,2011-01-01,2011-January-01,02:00
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13,2011-01,2011-01-01,2011-January-01,03:00
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1,2011-01,2011-01-01,2011-January-01,04:00

In [43]:
# change all column names to Capital Case
data_df.columns = data_df.columns.str.capitalize()
data_df.head()

,Date,Season,Holiday,Workingday,Weather,Temp,Atemp,Humidity,Windspeed,Casual,Registered,Count,Date_2,Date_3,Date_4,Hour
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16,2011-01,2011-01-01,2011-January-01,00:00
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40,2011-01,2011-01-01,2011-January-01,01:00
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32,2011-01,2011-01-01,2011-January-01,02:00
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13,2011-01,2011-01-01,2011-January-01,03:00
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1,2011-01,2011-01-01,2011-January-01,04:00

In [49]:
# get availables values in a column
print("Size:", data_df['Casual'].size)
print("Unique", len(data_df['Casual'].unique()))

Size: 10886
Unique 309

In [57]:
# get missing values using isnull()
data_damaged_df = pd.read_csv('bikes_damage.csv')
print(data_damaged_df.info())
print("*"*50)
data_damaged_df[ data_damaged_df['weather'].isnull() ]

<class 'pandas.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  str
 1   season      10878 non-null  float64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10877 non-null  float64
 5   temp        10882 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(5), int64(6), str(1)
memory usage: 1020.7 KB
None
**************************************************

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
1,2011-01-01 01:00:00,1.0,0,0,NaN,NaN,13.635,80,0.0000,8,32,40
6,2011-01-01 06:00:00,1.0,0,0,NaN,9.02,13.635,80,0.0000,2,0,2
10,2011-01-01 10:00:00,1.0,0,0,NaN,15.58,19.695,76,16.9979,12,24,36
29,2011-01-02 06:00:00,1.0,0,0,NaN,17.22,21.210,77,19.9995,0,2,2
62,2011-01-03 17:00:00,1.0,0,1,NaN,9.84,11.365,30,15.0013,11,146,157
134,2011-01-06 20:00:00,1.0,0,1,NaN,8.20,10.605,51,11.0014,3,66,69
638,2011-02-09 19:00:00,1.0,0,1,NaN,5.74,6.060,86,16.9979,1,87,88
1286,2011-03-18 11:00:00,1.0,0,1,NaN,22.14,25.760,52,19.0012,55,104,159
1790,2011-05-01 12:00:00,2.0,0,0,NaN,19.68,23.485,77,7.0015,109,172,281

In [58]:
data_damaged_df.isnull().sum()

datetime      0
season        8
holiday       0
workingday    0
weather       9
temp          4
atemp         0
humidity      0
windspeed     0
casual        0
registered    0
count         0
dtype: int64

In [ ]:
import numpy as np

# fill missing values using fillna()
print("Fill missing with FillNA:\n", )


# fill missing attention_time with average time
print("Fill missing attention_time with average time:\n", )

# fill missing city with not reported
print("Fill missing city with not reported:\n", )

# fill missing values using fillna() in date_time column with interopolation
print("Fill missing values using fillna() in date_time column with interpolation:\n", )

In [ ]:
# drop missing values using dropna()
print("Drop missing values using dropna():\n", )